name: Terraform Workflow

on:
  push:
    branches:
      - main

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.5.0  # Specify the desired Terraform version

      - name: Set up Azure Credentials
        run: |
          echo "${{ secrets.AZURE_CREDENTIALS }}" > $GITHUB_WORKSPACE/azure_credentials.json

      - name: Output Azure Credentials for Debugging
        run: cat $GITHUB_WORKSPACE/azure_credentials.json
        # Comment this out after debugging to avoid exposing secrets

      - name: Login to Azure
        run: |
          echo "Logging in to Azure..."
          CLIENT_ID=$(jq -r .clientId $GITHUB_WORKSPACE/azure_credentials.json)
          CLIENT_SECRET=$(jq -r .clientSecret $GITHUB_WORKSPACE/azure_credentials.json)
          TENANT_ID=$(jq -r .tenantId $GITHUB_WORKSPACE/azure_credentials.json)

          echo "Client ID: $CLIENT_ID"  # Optional debug output
          echo "Tenant ID: $TENANT_ID"  # Optional debug output

          az login --service-principal -u "$CLIENT_ID" -p "$CLIENT_SECRET" --tenant "$TENANT_ID" || { echo 'Azure login failed'; exit 1; }

      - name: Terraform Init
        run: terraform init

      - name: Terraform Plan
        run: terraform plan

      - name: Terraform Apply
        run: terraform apply -auto-approve
